//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace priut.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAnim
    {
        public int ID_DataAnim { get; set; }
        public Nullable<int> ID_passport_FK_ { get; set; }
        public Nullable<int> ID_MedData_FK_ { get; set; }
        public Nullable<int> ID_stay_FK_ { get; set; }
    
        public virtual MedData MedData { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Stay Stay { get; set; }
    }
}
