//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace priut.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedData()
        {
            this.DataAnim = new HashSet<DataAnim>();
        }
    
        public int ID_MedData { get; set; }
        public string AvailabilityOfVaccinations { get; set; }
        public string InitialState { get; set; }
        public Nullable<int> ID_medical_FK_ { get; set; }
        public Nullable<int> ID_Sotr_FK_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataAnim> DataAnim { get; set; }
        public virtual HistoryMedical HistoryMedical { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
