//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace priut.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StayStr
    {
        public int ID_StayStr { get; set; }
        public int ID_Vol_FK_ { get; set; }
        public Nullable<int> ID_Sotr_FK_ { get; set; }
        public Nullable<int> ID_stay_FK_ { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Stay Stay { get; set; }
        public virtual Volunteers Volunteers { get; set; }
    }
}
